# Netlify build configuration for Neat Starter (Eleventy + Tailwind)

[build]
  command = "npm run build"
  publish = "_site"
[build.environment]
  NODE_VERSION = "18"
  
# Local development with `netlify dev`
[dev]
  command = "npm start"
  port = 8888
  publish = "_site"

# Netlify Functions (if you add any under netlify/functions)
[functions]
  directory = "netlify/functions"
