backend:
  name: github
  repo: jimslaughter/neat-starter-site
  branch: main
  base_url: https://neat-starter-site.pages.dev
  auth_endpoint: /api/auth

media_folder: "src/static/img"
public_folder: "/static/img"
local_backend: true

# Use the proxy when editing locally so you can log in without OAuth
#   Terminal A: npx netlify-cms-proxy-server
#   Terminal B: npm start  →  http://localhost:8080/admin
local_backend: true

# Uncomment if you want Draft → Review → Publish workflow in CMS
# publish_mode: editorial_workflow

# Optional: safer slugs for filenames/paths
slug:
  encoding: "unicode"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    # Filenames will follow the slug (title → slug)
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured", name: "featured", widget: "boolean", required: false, default: false }
      - { label: "Draft (don’t publish)", name: "draft", widget: "boolean", required: false, default: false }
      - { label: "Thumbnail", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        default: ["post"]
        required: false

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: "Nav Items"
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: "Title", name: text, widget: string }
              - { label: "URL", name: url, widget: string }

      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: "Nav Items"
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: "Title", name: title, widget: string }
              - { label: "URL", name: url, widget: string }
              - { label: "Description", name: desc, widget: string }

      - label: "Meta Settings"
        name: "meta"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Name", name: name, widget: string }
          - { label: "Author", name: author, widget: string }
          - { label: "URL", name: url, widget: string }
